// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CC.CodeGenerator.Demo.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CC.CodeGenerator.Demo.Entity.Configurations
{
    public partial class CityConfiguration : IEntityTypeConfiguration<City>
    {
        public void Configure(EntityTypeBuilder<City> entity)
        {
            entity.Property(e => e.CityId).HasComment("城市");

            entity.Property(e => e.CityTitle).HasComment("名称");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<City> entity);
    }
}
