// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CC.CodeGenerator.Demo.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CC.CodeGenerator.Demo.Entity.Configurations
{
    public partial class PeopleConfiguration : IEntityTypeConfiguration<People>
    {
        public void Configure(EntityTypeBuilder<People> entity)
        {
            entity.Property(e => e.PeopleId)
                .ValueGeneratedNever()
                .HasComment("人员");

            entity.Property(e => e.Age).HasComment("年龄");

            entity.Property(e => e.CityId).HasComment("城市编号");

            entity.Property(e => e.Name).HasComment("姓名");

            entity.Property(e => e.Sex).HasComment("性别");

            entity.HasOne(d => d.City)
                .WithMany(p => p.People)
                .HasForeignKey(d => d.CityId)
                .HasConstraintName("FK_People_City1");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<People> entity);
    }
}
