// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CC.CodeGenerator.Demo.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CC.CodeGenerator.Demo.Entity.Configurations
{
    public partial class PeopleConfiguration : IEntityTypeConfiguration<People>
    {
        public void Configure(EntityTypeBuilder<People> entity)
        {
            entity.Property(e => e.PeopleId)
                .ValueGeneratedNever()
                .HasComment("12");

            entity.Property(e => e.Age).HasComment("90");

            entity.Property(e => e.Name).HasComment("56");

            entity.Property(e => e.Sex).HasComment("78");

            entity.Property(e => e.UserName).HasComment("34");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<People> entity);
    }
}
