// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CC.CodeGenerator.Demo.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CC.CodeGenerator.Demo.Entity.Configurations
{
    public partial class PersonnelConfiguration : IEntityTypeConfiguration<Personnel>
    {
        public void Configure(EntityTypeBuilder<Personnel> entity)
        {
            entity.Property(e => e.PersonnelId).ValueGeneratedNever();

            entity.HasOne(d => d.Company)
                .WithMany(p => p.Personnel)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Personnel_Company");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Personnel> entity);
    }
}
