// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CC.CodeGenerator.Demo.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace CC.CodeGenerator.Demo.Entity.Configurations
{
    public partial class SCDemoConfiguration : IEntityTypeConfiguration<SCDemo>
    {
        public void Configure(EntityTypeBuilder<SCDemo> entity)
        {
            entity.HasKey(e => new { e.A1, e.A2 });

            entity.Property(e => e.A3).IsFixedLength();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SCDemo> entity);
    }
}
