// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.CodeGenerator.Demo.Entity
{
    public partial class Address
    {
        public Address()
        {
            Company = new HashSet<Company>();
        }

        [Key]
        public Guid AddressId { get; set; }
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("Address")]
        public virtual ICollection<Company> Company { get; set; }
    }
}