// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.CodeGenerator.Demo.Entity
{
    public partial class City
    {
        public City()
        {
            People = new HashSet<People>();
        }

        /// <summary>
        /// 城市
        /// </summary>
        [Key]
        [StringLength(50)]
        public string CityId { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        [StringLength(50)]
        public string CityTitle { get; set; }

        [InverseProperty("City")]
        public virtual ICollection<People> People { get; set; }
    }
}