// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.CodeGenerator.Demo.Entity
{
    public partial class Company
    {
        public Company()
        {
            Personnel = new HashSet<Personnel>();
        }

        [Key]
        public Guid CompanyId { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public Guid? AddressId { get; set; }

        [ForeignKey("AddressId")]
        [InverseProperty("Company")]
        public virtual Address Address { get; set; }
        [InverseProperty("Company")]
        public virtual ICollection<Personnel> Personnel { get; set; }
    }
}