// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.CodeGenerator.Demo.Entity
{
    public partial class People
    {
        public People()
        {
            Skill = new HashSet<Skill>();
        }

        /// <summary>
        /// 人员
        /// </summary>
        [Key]
        public Guid PeopleId { get; set; }
        /// <summary>
        /// 姓名
        /// </summary>
        [StringLength(50)]
        public string Name { get; set; }
        /// <summary>
        /// 性别
        /// </summary>
        [StringLength(50)]
        public string Sex { get; set; }
        /// <summary>
        /// 年龄
        /// </summary>
        public int? Age { get; set; }
        /// <summary>
        /// 城市编号
        /// </summary>
        [StringLength(50)]
        public string CityId { get; set; }

        [ForeignKey("CityId")]
        [InverseProperty("People")]
        public virtual City City { get; set; }
        [InverseProperty("People")]
        public virtual ICollection<Skill> Skill { get; set; }
    }
}