// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.CodeGenerator.Demo.Entity
{
    public partial class Personnel
    {
        [Key]
        public Guid PersonnelId { get; set; }
        public Guid CompanyId { get; set; }
        [StringLength(50)]
        public string Name { get; set; }
        public int? Age { get; set; }

        [ForeignKey("CompanyId")]
        [InverseProperty("Personnel")]
        public virtual Company Company { get; set; }
    }
}