// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.CodeGenerator.Demo.Entity
{
    public partial class SCDemo
    {
        [Key]
        public Guid A1 { get; set; }
        [Key]
        public Guid A2 { get; set; }
        [StringLength(10)]
        public string A3 { get; set; }
    }
}