// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.CodeGenerator.Demo.Entity
{
    public partial class Skill
    {
        /// <summary>
        /// 技能
        /// </summary>
        [Key]
        public Guid SkillId { get; set; }
        /// <summary>
        /// 人员
        /// </summary>
        public Guid PeopleId { get; set; }
        /// <summary>
        /// 技能名称
        /// </summary>
        [StringLength(50)]
        public string SkillName { get; set; }

        [ForeignKey("PeopleId")]
        [InverseProperty("Skill")]
        public virtual People People { get; set; }
    }
}