// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.CodeGenerator.DemoEntity;

public partial class Achievements
{
    [Key]
    public Guid AchievementsId { get; set; }

    /// <summary>
    /// 员工
    /// </summary>
    public Guid PersonnelId { get; set; }

    public int? Year { get; set; }

    [StringLength(50)]
    public string Level { get; set; }

    [ForeignKey("PersonnelId")]
    [InverseProperty("Achievements")]
    public virtual Personnel Personnel { get; set; }
}