// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.CodeGenerator.DemoEntity;

public partial class Company
{
    /// <summary>
    /// 企业
    /// </summary>
    [Key]
    public Guid CompanyId { get; set; }

    /// <summary>
    /// 名称
    /// </summary>
    [StringLength(50)]
    public string Title { get; set; }

    /// <summary>
    /// 地址
    /// </summary>
    [Required]
    [StringLength(200)]
    public string Address { get; set; }

    [InverseProperty("Company")]
    public virtual ICollection<Personnel> Personnel { get; } = new List<Personnel>();
}