// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CC.CodeGenerator.DemoEntity;

public partial class Personnel
{
    /// <summary>
    /// 员工
    /// </summary>
    [Key]
    public Guid PersonnelId { get; set; }

    /// <summary>
    /// 企业
    /// </summary>
    public Guid CompanyId { get; set; }

    /// <summary>
    /// 姓名
    /// </summary>
    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    /// <summary>
    /// 性别
    /// </summary>
    [StringLength(50)]
    public string Gender { get; set; }

    /// <summary>
    /// 生日
    /// </summary>
    [Column(TypeName = "date")]
    public DateTime? Birthday { get; set; }

    /// <summary>
    /// 是否在职
    /// </summary>
    public bool IsJob { get; set; }

    [InverseProperty("Personnel")]
    public virtual ICollection<Achievements> Achievements { get; } = new List<Achievements>();

    [ForeignKey("CompanyId")]
    [InverseProperty("Personnel")]
    public virtual Company Company { get; set; }
}